services:
  - type: web
    name: coca-the-shark
    env: php
    plan: free
    buildCommand: 'composer install && npm install && npm run dev'
    startCommand: 'php artisan serve --host 0.0.0.0 --port 10000'
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://coca-the-shark.onrender.com
    domains:
      - coca-the-shark.onrender.com